/** @type {import('tailwindcss').Config} */
export default {
	content: [
		'./src/**/*.{js,ts,jsx,tsx}',
	],
	safelist: [
		'atomic-flex-row-reverse',
		'atomic-flex-row',
		'atomic-bg-gradient-to-r',
		'atomic-border-primary-default',
		'hover:atomic-border-primary-hover',
		'hover:atomic-text-primary-hover',
		'atomic-bg-primary-default',
		'hover:atomic-bg-primary-hover',
		'hover:atomic-from-primary-left-hover',
		'hover:atomic-to-primary-right-hover',
		'atomic-from-primary-left',
		'atomic-to-primary-right',
		'atomic-text-primary-text',
		'atomic-text-primary-default',
		'atomic-text-primary-hover',
		'atomic-border-secondary-default',
		'hover:atomic-border-secondary-hover',
		'hover:atomic-text-secondary-hover',
		'atomic-bg-secondary-default',
		'hover:atomic-bg-secondary-hover',
		'hover:atomic-from-secondary-left-hover',
		'hover:atomic-to-secondary-right-hover',
		'atomic-from-secondary-left',
		'atomic-to-secondary-right',
		'atomic-text-secondary-text',
		'atomic-text-secondary-default',
		'atomic-text-secondary-hover',
		'atomic-border-danger-default',
		'hover:atomic-border-danger-hover',
		'hover:atomic-text-danger-hover',
		'atomic-bg-danger-default',
		'hover:atomic-bg-danger-hover',
		'hover:atomic-from-danger-left-hover',
		'hover:atomic-to-danger-right-hover',
		'atomic-from-danger-left',
		'atomic-to-danger-right',
		'atomic-text-danger-text',
		'atomic-text-danger-default',
		'atomic-text-danger-hover',
		'atomic-border-warning-default',
		'hover:atomic-border-warning-hover',
		'hover:atomic-text-warning-hover',
		'atomic-bg-warning-default',
		'hover:atomic-bg-warning-hover',
		'hover:atomic-from-warning-left-hover',
		'hover:atomic-to-warning-right-hover',
		'atomic-from-warning-left',
		'atomic-to-warning-right',
		'atomic-text-warning-text',
		'atomic-text-warning-default',
		'atomic-text-warning-hover',
		'atomic-border-success-default',
		'hover:atomic-border-success-hover',
		'hover:atomic-text-success-hover',
		'atomic-bg-success-default',
		'hover:atomic-bg-success-hover',
		'hover:atomic-from-success-left-hover',
		'hover:atomic-to-success-right-hover',
		'atomic-from-success-left',
		'atomic-to-success-right',
		'atomic-text-success-text',
		'atomic-text-success-default',
		'atomic-text-success-hover',
		'atomic-border-info-default',
		'hover:atomic-border-info-hover',
		'hover:atomic-text-info-hover',
		'atomic-bg-info-default',
		'hover:atomic-bg-info-hover',
		'hover:atomic-from-info-left-hover',
		'hover:atomic-to-info-right-hover',
		'atomic-from-info-left',
		'atomic-to-info-right',
		'atomic-text-info-text',
		'atomic-text-info-default',
		'atomic-text-info-hover',
		'atomic-border-light-default',
		'hover:atomic-border-light-hover',
		'hover:atomic-text-light-hover',
		'atomic-bg-light-default',
		'hover:atomic-bg-light-hover',
		'hover:atomic-from-light-left-hover',
		'hover:atomic-to-light-right-hover',
		'atomic-from-light-left',
		'atomic-to-light-right',
		'atomic-text-light-text',
		'atomic-text-light-default',
		'atomic-text-light-hover',
		'atomic-border-dark-default',
		'hover:atomic-border-dark-hover',
		'hover:atomic-text-dark-hover',
		'atomic-bg-dark-default',
		'hover:atomic-bg-dark-hover',
		'hover:atomic-from-dark-left-hover',
		'hover:atomic-to-dark-right-hover',
		'atomic-from-dark-left',
		'atomic-to-dark-right',
		'atomic-text-dark-text',
		'atomic-text-dark-default',
		'atomic-text-dark-hover',
		'disabled:hover:atomic-bg-primary-default',
		'disabled:hover:atomic-bg-secondary-default',
		'disabled:hover:atomic-bg-warning-default',
		'disabled:hover:atomic-bg-success-default',
		'disabled:hover:atomic-bg-danger-default',
		'disabled:hover:atomic-bg-info-default',
		'disabled:hover:atomic-bg-light-default',
		'disabled:hover:atomic-bg-dark-default',
		'disabled:hover:atomic-to-primary-right',
		'disabled:hover:atomic-to-secondary-right',
		'disabled:hover:atomic-to-warning-right',
		'disabled:hover:atomic-to-success-right',
		'disabled:hover:atomic-to-danger-right',
		'disabled:hover:atomic-to-info-right',
		'disabled:hover:atomic-to-light-right',
		'disabled:hover:atomic-to-dark-right',
		'disabled:hover:atomic-from-primary-left',
		'disabled:hover:atomic-from-secondary-left',
		'disabled:hover:atomic-from-warning-left',
		'disabled:hover:atomic-from-success-left',
		'disabled:hover:atomic-from-danger-left',
		'disabled:hover:atomic-from-info-left',
		'disabled:hover:atomic-from-light-left',
		'disabled:hover:atomic-from-dark-left',
		'disabled:hover:atomic-border-primary-default',
		'disabled:hover:atomic-border-secondary-default',
		'disabled:hover:atomic-border-warning-default',
		'disabled:hover:atomic-border-success-default',
		'disabled:hover:atomic-border-danger-default',
		'disabled:hover:atomic-border-info-default',
		'disabled:hover:atomic-border-light-default',
		'disabled:hover:atomic-border-dark-default',
		'disabled:hover:atomic-text-primary-default',
		'disabled:hover:atomic-text-secondary-default',
		'disabled:hover:atomic-text-warning-default',
		'disabled:hover:atomic-text-success-default',
		'disabled:hover:atomic-text-info-default',
		'disabled:hover:atomic-text-primary-default',
		'disabled:hover:atomic-text-light-default',
		'disabled:hover:atomic-text-dark-default',
	],
	theme: {
		extend: {
			colors: {
				primary: {
					default: '#C026D3',
					left: '#EC4899',
					'left-hover': '#DB2777',
					right: '#A855F7',
					'right-hover': '#9333EA',
					hover: '#A21CAF',
					text: '#F8FAFC',
				},
				secondary: {
					default: '#64748B',
					left: '#CBD5E1',
					'left-hover': '#94A3B8',
					right: '#64748b',
					'right-hover': '#475569',
					hover: '#475569',
					text: '#F8FAFC',
				},
				danger: {
					default: '#F43F5E',
					left: '#FB7185',
					'left-hover': '#F43F5E',
					right: '#DC2626',
					'right-hover': '#B91C1C',
					hover: '#E11D48',
					text: '#F8FAFC',
				},
				warning: {
					default: '#F59E0B',
					left: '#FACC15',
					'left-hover': '#EAB308',
					right: '#F97316',
					'right-hover': '#EA580C',
					hover: '#D97706',
					text: '#F8FAFC',
				},
				success: {
					default: '#22C55E',
					left: '#BEF264',
					'left-hover': '#A3E635',
					right: '#10B981',
					'right-hover': '#059669',
					hover: '#16A34A',
					text: '#F8FAFC',
				},
				info: {
					default: '#0EA5E9',
					left: '#22D3EE',
					'left-hover': '#06B6D4',
					right: '#2563EB',
					'right-hover': '#1D4ED8',
					hover: '#0284C7',
					text: '#F8FAFC',
				},
				light: {
					default: '#F1F5F9',
					left: '#F8FAFC',
					'left-hover': '#F1F5F9',
					right: '#E2E8F0',
					'right-hover': '#CBD5E1',
					hover: '#E2E8F0',
					text: '#1E293B',
				},
				dark: {
					default: '#1E293B',
					left: '#475569',
					'left-hover': '#334155',
					right: '#0F172A',
					'right-hover': '#000000',
					hover: '#0F172A',
					text: '#F8FAFC',
				},
			},
		},
	},
	plugins: [],
	prefix: 'atomic-',
};